package model;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

public class Try1 {

    //This method creates an JSONArray of labels in which those are generated by their positions

    public static void writeSomeFile() {
        JSONObject myjson = new JSONObject();
        myjson.put("type","minecraft:crafting_shaped");
        JSONArray ingredients = new JSONArray();
        ingredients.put(new JSONObject("{\"item\": \"minecraft:oak_log\"}"));
        myjson.put("ingredients",ingredients);

        JSONObject result = new JSONObject();
        result.put("item", "minecraft:oak_planks");
        result.put("count", 4);
        myjson.put("result", result);

        try {
            Writer file = new FileWriter("oak_chop_recipe.json");
            myjson.write(file);
            file.flush();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    static String readFile(String path, Charset encoding) throws IOException {
        byte[] encoded = Files.readAllBytes(Paths.get(path));
        return new String(encoded,encoding);
    }

    public static JSONObject readSomeFile() throws IOException {
        return new JSONObject(readFile("oak_chop_recipe.json", StandardCharsets.US_ASCII));
//        try (FileReader reader = new FileReader("oak_chop_recipe.json")) {
//
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
    }
}
